server:
  port: 8080
  servlet:
    context-path: /community  # 项目路径
spring:
  thymeleaf:
    cache: false  # 关闭缓存
  datasource:
    url: jdbc:mysql://localhost:3306/community
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 9
      min-idle: 5  # 最小空闲池
      min-evictable-idle-time-millis: 30000  # 最小空闲池等待时间，即超过30秒后，才释放连接
mybatis-plus:
  configuration:
    use-generated-keys: true
